[package]
edition = "2024"
name    = "git_sshripped_fuzz"
publish = false
readme  = "README.md"
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
anyhow                   = { workspace = true, features = ["std"] }
git_sshripped_encryption = { workspace = true }
libfuzzer-sys            = "0.4"

[[bin]]
bench = false
doc   = false
name  = "encryption_decrypt"
path  = "fuzz_targets/encryption_decrypt.rs"
test  = false

[[bin]]
bench = false
doc   = false
name  = "filter_pkt_protocol"
path  = "fuzz_targets/filter_pkt_protocol.rs"
test  = false
